name: deploy

on:
  workflow_dispatch:
    inputs:
      deploy_environment:
        description: 'The environment to deploy to'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DEPLOY_ENV: ${{ github.event.inputs.deploy_environment }}
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: bash ./deploy.sh
